#!/usr/bin/env bash

user=$(whoami)

info() {
    echo "[INFO] $1";
}

success() {
    echo "[SUCCESS] $1";
}

case "$1" in
    "compile")
    (
        info "Starting to compile application..."

        mvn clean package
    )
    ;;
    "run")
    (
        info "Running application..."

		sudo java -jar target/Motivatation.jar

        success "Succesfully exited application!"
    )
    ;;
    *)
        echo "Hello $user lets get this party started shall we!"
        echo ""
        echo "Motivate is a simple build tool command. This provides"
		    echo "a variety of commands to build, run and manage Motivatation."
        echo ""
        echo " Available commands:"
        echo "  * compile | Compile the project with Java 8."
        echo "  * run | Run the complete and compiled project."
        echo ""
    ;;
esac